# Generated by Django 2.1.5 on 2022-04-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
